### PR TITLE
Reformattet Lines + Temp Console Spam fix

### PR DESCRIPTION
**Pull request by hasezoey**
Reformattet some lines,
Changed so that it not outputs much to the Console, 
( https://github.com/mrmakeit/OCJS/blob/master-1.12.2/src/main/resources/bios.js#L1 )
Added Some `;` to some lines,
Optimized Some `if`'s

### CODE REVIEW

**Comment by mrmakeit** [comment]
This looks good, but I'd prefer if printToConsole were true by default.  I'd rather have the user intentionally disable the logging for now.  Unfortunately, too often someone will post an error without context, and those prints help with debugging.

Also, can you request the merge against the 1.10.2 branch?  That's the current build master, and it get's messy trying to merge down from other versions.

**Comment by hasezoey** [comment]
> Also, can you request the merge against the 1.10.2 branch? That's the current build master, and it get's messy trying to merge down from other versions.

i would, but saw the 1.12.2, i only testet it there so i would commit it there ^^

**Comment by hasezoey** [comment]
+ sorry never done something on github except write issues, so i may be slow in finding something ^^ (like merge / change base branch)

**Comment by mrmakeit** [comment]
Unfortunately, by changing the base that way, you are introducing commits for other mc versions.  You'll need to make the edits directly on the master-1.10.2 branch, not the master-1.12.2 branch.

**Comment by mrmakeit** [comment]
I don't think you'll be able to make the changes inside this pr, so I'm going to go ahead and close it.  Feel free to open a new one if you can get the branches corrected.

**Comment by hasezoey** [comment]
ok, this means edit the file in the branch directly? ("open new pull"?) - sorry ^^"

**Comment by mrmakeit** [comment]
yes.

**Pull request closed without merging**
