### PR TITLE
changes

### PR DESCRIPTION
**Pull request by hasezoey**
1. renameing dec2String to decodeRead
2. adding missing semicolons
3. prettifying functions from `var name = function() {}` to `function name() {}`
4. try catch block in the eval (to show it on screen)

### CODE REVIEW

**Comment by hasezoey** [comment]
i think it was the last commit i made to the patch

**Comment by mrmakeit** [comment]
I'd prefer it if there was a way to convert the JSDoc version of the eeprom file into the version loaded by the mod.  Manually mirroring the files is a pain, and there should be a way to automate it.  If you can add that, I'll merge this in.

**Comment by hasezoey** [comment]
there is already, made some hours before you wrote it
https://github.com/hasezoey/Strip-Comments

**Comment by hasezoey** [comment]
i will close this pull request for now, until a stable version of the OS is there

and @mrmakeit eventually add the OS as a git submodule

**Pull request closed without merging**
